### ISSUE TITLE
Split Altair MooseFS chunkserver into 4

### ISSUE THREAD

**Issue by Zorlin** [application-research/estuary-hosted-infrastructure#22]
We're moving towards 4+2 erasure coding, migrating from 2 chunkservers (and straight 2x replication). This will require a temporary outage where we split a JBOD into four parts, and connect it to four independent chunkservers. We'll do one JBOD at a time, to minimise the number of chunks that go unavailable during that time.

This covers the first phase

**Comment by PC-Admin** [comment]
Nicely done!
