### ISSUE TITLE
Provision Infra for Taubyte

### ISSUE THREAD

**Issue by jlogelin** [application-research/estuary-hosted-infrastructure#34]
Per Samy from Taubyte via [slack](https://filecoinproject.slack.com/archives/C059P2R1869/p1686590916324349):
 
> If we can have the following config, we could start with a first deployment done over a call (later this week or early next week works for me):
> - 3-to-5 VMs or Servers with +32GB or RAM and +512GB of hard-drive. Ubuntu 22.04 preferred
> - 1 public IP per host
> This will allow me to demonstrate deployment using spore-drive and we will have a test network ready.
> After that, I suggest a call to go over the features to be exposed through webassembly. The goal is to bootstrap (minimal integration) the integration with Delta or any other Filecoin data tools project you decide to start with.
> Once we have a minimal plugin (might take a week depending on how hard it is to setup a test environment for the selected tool) we should collaborate to move it forward.
> Tools available to test the plugin:
> Dreamland - a local network
> Spore-drive - create at least one other network for staging (+preferably a 2 VMs, network per developer)

**Comment by Zorlin** [comment]
Partially fixed by 09e90934575664b77cd363df9d127099d4c889c6 in `estuary-hosted-infrastructure`

**Comment by Zorlin** [comment]
The IPs we assigned were in the staff range, we've since moved them into a new customer/partner range, so re-deploying now.

**Comment by Zorlin** [comment]
Mostly complete now (they have working VMs and the needed access, and are beginning integrations). some final remaining network issues to sort out.
